# Week 1 project:
- Import a csv file 'wine-ratings.csv', filtering out rows based on data specified
- Save selected rows to a new JSON file

**Import pandas and initialize dataframe**

In [40]:
import pandas as pd
df = pd.read_csv(r"./wine-ratings.csv", index_col=0)

df.head()

,name,grape,region,variety,rating,notes
0,1000 Stories Bourbon Barrel Aged Batch Blue Ca...,NaN,"Mendocino, California",Red Wine,91.0,"This is a very special, limited release of 100..."
1,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,89.0,The California Gold Rush was a period of coura...
2,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,90.0,The California Gold Rush was a period of coura...
3,1000 Stories Bourbon Barrel Aged Zinfandel 2013,NaN,"North Coast, California",Red Wine,91.0,"The wine has a deep, rich purple color. An int..."
4,1000 Stories Bourbon Barrel Aged Zinfandel 2014,NaN,California,Red Wine,90.0,Batch #004 is the first release of the 2014 vi...

**Get rid of 'grape' column since it's empty**

In [41]:
df.drop('grape', axis='columns', inplace=True)
df.head()

,name,region,variety,rating,notes
0,1000 Stories Bourbon Barrel Aged Batch Blue Ca...,"Mendocino, California",Red Wine,91.0,"This is a very special, limited release of 100..."
1,1000 Stories Bourbon Barrel Aged Gold Rush Red...,California,Red Wine,89.0,The California Gold Rush was a period of coura...
2,1000 Stories Bourbon Barrel Aged Gold Rush Red...,California,Red Wine,90.0,The California Gold Rush was a period of coura...
3,1000 Stories Bourbon Barrel Aged Zinfandel 2013,"North Coast, California",Red Wine,91.0,"The wine has a deep, rich purple color. An int..."
4,1000 Stories Bourbon Barrel Aged Zinfandel 2014,California,Red Wine,90.0,Batch #004 is the first release of the 2014 vi...

**Filter data by**
1) variety - White Wine
2) rating >= 90
3) region - France, Italy

**Filter by white wines only**

In [42]:
df = df.loc[df['variety'] == 'White Wine']
df.head()

,name,region,variety,rating,notes
12,14 Hands Chardonnay 2011,Washington,White Wine,89.0,This Chardonnay displays aromas and flavors of...
16,14 Hands Riesling 2014,Washington,White Wine,88.0,This crisp Riesling shows bright flavors of ap...
17,14 Hands Riesling 2015,Washington,White Wine,88.0,This crisp Riesling shows bright flavors of ap...
18,14 Hands Riesling 2016,Washington,White Wine,88.0,This crisp Riesling shows bright flavors of ap...
26,1865 Single Vineyard Sauvignon Blanc 2011,Chile,White Wine,91.0,"Almost transparent pale yellow, young, with gr..."

**Filter by ratings >= 90**

In [43]:
df = df.loc[df['rating'] >= 90]
df.head()

,name,region,variety,rating,notes
26,1865 Single Vineyard Sauvignon Blanc 2011,Chile,White Wine,91.0,"Almost transparent pale yellow, young, with gr..."
27,1865 Single Vineyard Sauvignon Blanc 2013,Chile,White Wine,90.0,"A brilliant, pale, almost transparent yellow w..."
28,1865 Single Vineyard Sauvignon Blanc 2014,"Leyda Valley, San Antonio Valley (Chile), Chile",White Wine,90.0,"A brilliant, pale, almost transparent yellow w..."
29,1865 Single Vineyard Sauvignon Blanc 2015,"Leyda Valley, San Antonio Valley (Chile), Chile",White Wine,91.0,"A brilliant, pale, almost transparent yellow w..."
44,3 Stones Sauvignon Blanc 2008,"Marlborough, New Zealand",White Wine,90.0,3 Stones is New Zealand wine emblazoned with a...

**Filer by region from either France or Italy**

Since the regions are not straightforward/direct we look for partial strings

In [44]:
df = df.loc[df['region'].str.contains('Italy|France')]
df

,name,region,variety,rating,notes
173,Abbazia di Novacella Gewurztraminer 2007,"Trentino-Alto Adige, Italy",White Wine,90.0,"Typical white wine, elegant and aromatic, ligh..."
174,Abbazia di Novacella Gruner Veltliner 2017,"Alto Adige, Trentino-Alto Adige, Italy",White Wine,90.0,This wine offers fresh green apple aromas and ...
175,Abbazia di Novacella Kerner 2007,"Trentino-Alto Adige, Italy",White Wine,91.0,The color goes from pale straw yellow with gre...
176,Abbazia di Novacella Kerner 2016,"Trentino-Alto Adige, Italy",White Wine,91.0,"An aromatic white wine, which has become a spe..."
177,Abbazia di Novacella Kerner 2017,"Trentino-Alto Adige, Italy",White Wine,94.0,100% Kerner from gravelly marine soils planted...
...,...,...,...,...,...
32575,Leone de Castris Verdeca Bianco Messapia 2009,Italy,White Wine,90.0,"Made from 100% Verdeca, an ancient Greek varie..."
32654,Les Cretes Les Abeilles 2006,"Valle d'Aosta, Italy",White Wine,91.0,Brilliant golden yellow hue. Fruit (dried apri...
32655,Les Cretes Valle d'Aosta Chardonnay 2010,Italy,White Wine,92.0,Valle d'Aosta Chardonnay is a lovely yellow. T...
32656,Les Cretes Valle d'Aosta Cuvee Bois Chardonnay...,"Valle d'Aosta, Italy",White Wine,94.0,The opening to the nose ranges from banana to ...
32668,Les Hauts de Lagarde Bordeaux Blanc 2013,"Bordeaux, France",White Wine,91.0,NaN

**Reset index of the dataframe**

In [45]:
df.reset_index(drop=True, inplace=True)
df.head()

,name,region,variety,rating,notes
0,Abbazia di Novacella Gewurztraminer 2007,"Trentino-Alto Adige, Italy",White Wine,90.0,"Typical white wine, elegant and aromatic, ligh..."
1,Abbazia di Novacella Gruner Veltliner 2017,"Alto Adige, Trentino-Alto Adige, Italy",White Wine,90.0,This wine offers fresh green apple aromas and ...
2,Abbazia di Novacella Kerner 2007,"Trentino-Alto Adige, Italy",White Wine,91.0,The color goes from pale straw yellow with gre...
3,Abbazia di Novacella Kerner 2016,"Trentino-Alto Adige, Italy",White Wine,91.0,"An aromatic white wine, which has become a spe..."
4,Abbazia di Novacella Kerner 2017,"Trentino-Alto Adige, Italy",White Wine,94.0,100% Kerner from gravelly marine soils planted...

**Convert df to formatted json**

Other formatting options (orient values)
- 'split’, ‘records’, ‘index’, ‘columns’, ‘values’

In [51]:
df.to_json('filtered-wine-ratings.json', orient='index', indent=4)